### ISSUE TITLE
Problem with installation on Windows 7

### ISSUE THREAD

**Issue by baeyal** [weinbe58/QuSpin#19]
Hello,
I installed quspin on my computer but then when I tried to run a script I got the following error:

Traceback (most recent call last):
  File "spin.py", line 1, in <module>
    from quspin.operators import hamiltonian # Hamiltonians and operators
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\__init__.py", line 2, in <module>
    from . import operators
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\operators\__init__.py", line 1, in <module>
    from .ops import *
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\operators\ops.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\basis\__init__.py", line 1, in <module>
    from .basis_1d import spin_basis_1d
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\basis\basis_1d\__init__.py", line 1, in <module>
    from .spin import spin_basis_1d
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\basis\basis_1d\spin.py", line 1, in <module>
    from ..base import basis,MAXPRINT
  File "C:\Users\Eyal\Anaconda\lib\site-packages\quspin\basis\base.py", line 1, in <module>
    import numpy as _np
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\core\__init__.py", line 25, in <module>
    from . import numeric
  File "C:\Users\Eyal\Anaconda\lib\site-packages\numpy\core\numeric.py", line 73, in <module>
    MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
AttributeError: 'module' object has no attribute 'MAY_SHARE_BOUNDS'

Thank you for the wonderful package,
Eyal

**Comment by mgbukov** [comment]
Phil, can it be that Anaconda (from the time before they introduced
anaconda2 and anaconda3 separately) is incompatible with the latest version
of numpy?

Marin

**Comment by baeyal** [comment]
Reinstalled anaconda and quspin as Marin suggested and it seems to work successfully. Thanks!
