### ISSUE TITLE
About the install QuSpin 0.3.2 local package in Linux and Oxs

### ISSUE THREAD

**Issue by zuozw** [weinbe58/QuSpin#195]
Hi, My cluster can not connect the internet. I download the quspin package(Linux python 3.7) and try install it from the local package, but I failed.
1) I use the _pip install quspin-0.3.2-py37hc37dcb4_0.tar.bz2_, get this:
Processing ./quspin-0.3.2-py37hc37dcb4_0.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/ll/9b3kfx6123521m3trp_nwz2m0000gn/T/pip-req-build-xd4680rn/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ll/9b3kfx6123521m3trp_nwz2m0000gn/T/pip-req-build-xd4680rn/
2) I unzip the bz2 file and use the _python setup.py install_ it still doesn't work.File "setup.py", line 11, in <module>
    setup(**configuration(top_path='').todict())
  File "setup.py", line 4, in configuration
    config.add_subpackage('basis')
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1037, in add_subpackage
    caller_level = 2)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1006, in get_subpackage
    caller_level = caller_level + 1)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 943, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "./basis/setup.py", line 42, in configuration
    config.add_subpackage('basis_1d')
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1037, in add_subpackage
    caller_level = 2)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1006, in get_subpackage
    caller_level = caller_level + 1)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 943, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "basis/basis_1d/setup.py", line 5, in configuration
    config.add_subpackage('_basis_1d_core')
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1037, in add_subpackage
    caller_level = 2)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1006, in get_subpackage
    caller_level = caller_level + 1)
  File "/anaconda3/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 943, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "basis/basis_1d/_basis_1d_core/setup.py", line 39, in configuration
    cython_files()
  File "basis/basis_1d/_basis_1d_core/setup.py", line 26, in cython_files
    cythonize(cython_src)
  File "/anaconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
    aliases=aliases)
  File "/anaconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/anaconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
    raise ValueError(error_msg)
ValueError: '/Users/Downloads/quspin-0.3.2-py37hc37dcb4_0/lib/python3.7/site-packages/quspin/basis/basis_1d/_basis_1d_core/hcp_basis.pyx' doesn't match any files

I have testes in Linux and Oxs, these methods do not work. I want to know to fix this.

**Comment by weinbe58** [comment]
Do you have access to anaconda on your cluster?

**Comment by zuozw** [comment]
> Do you have access to anaconda on your cluster?

Yes. I test the two methods in cluster(linux) and Mac.

**Comment by weinbe58** [comment]
so what happens if you run: 
```
$ conda install quspin-0.3.2-py37hc37dcb4_0.tar.bz2
```

**Comment by weinbe58** [comment]
I just tested this method and it seems to work, although you'll have to make sure you have installed the following packages:

numpy, scipy, dill, gmpy2, joblib, and six

**Comment by zuozw** [comment]
> I just tested this method and it seems to work, although you'll have to make sure you have installed the following packages:
> 
> numpy, scipy, dill, gmpy2, joblib, and six

OK, it works.
