### ISSUE TITLE
Cython issue after install

### ISSUE THREAD

**Issue by Sazbo7** [weinbe58/QuSpin#237]
Successfully install quspin on Mac OS High Sierra version 10.13.6 via conda with Cython version 0.29.12, but when importing in python scripts running into

from quspin.basis import spin_basis_1d

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/operators/__init__.py", line 52, in <module>
    from .quantum_operator_core import *
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/basis/__init__.py", line 108, in <module>
    from .basis_1d import *
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/basis/basis_1d/__init__.py", line 1, in <module>
    from .spin import spin_basis_1d
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/basis/basis_1d/spin.py", line 1, in <module>
    from ._basis_1d_core import hcp_basis,hcp_ops
  File "/Users/szabo.48/bin/anaconda3/envs/python3/lib/python3.7/site-packages/quspin/basis/basis_1d/_basis_1d_core/__init__.py", line 1, in <module>
    from . import hcp_basis,hcp_ops
  File "stringsource", line 105, in init quspin.basis.basis_1d._basis_1d_core.hcp_basis
AttributeError: type object 'quspin.basis.basis_1d._basis_1d_core.hcp_basis.arr' has no attribute '__reduce_cython__'

**Comment by weinbe58** [comment]
Could you give us some more I about what the exact issue is?

**Comment by Sazbo7** [comment]
Update: Reverted to Scipy 1.3.0 to Scipy 1.2.1 and no longer have issue when importing QuSpin libraries. Sorry, all of this in Python 3.7.4
