### ISSUE TITLE
quspin v0.3.4: incompatiblity with numba=0.49.0

### ISSUE THREAD

**Issue by jtschneider** [weinbe58/QuSpin#319]
Hello,
I encounter a strange bug after updating to the latest version 0.3.4 via my miniconda distro on a cluster, as well as a proper anaconda distro on my PC. 
So I uninstalled all my miniconda distros and reinstalled it completely fresh. The only command I entered before the error messages below, was `conda install -c weinbe58 omp quspin`.

As you can see below, the first error about numba can be fixed by manually importing it. However, it throws a different error about a missing cython function after importing: 

```python console
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quspin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/lib/python3.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "~/miniconda3/lib/python3.7/site-packages/quspin/operators/__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "~/miniconda3/lib/python3.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/__init__.py", line 118, in <module>
    from .basis_general import *
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/base_hcb.py", line 1, in <module>
    from ._basis_general_core import hcb_basis_core_wrap
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/_basis_general_core/__init__.py", line 6, in <module>
    from .user_core import user_core_wrap
  File "quspin/basis/basis_general/_basis_general_core/user_core.pyx", line 6, in init quspin.basis.basis_general._basis_general_core.user_core
ModuleNotFoundError: No module named 'numba.ccallback'
>>> import numba
>>> import quspin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/lib/python3.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "~/miniconda3/lib/python3.7/site-packages/quspin/operators/__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "~/miniconda3/lib/python3.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/__init__.py", line 118, in <module>
    from .basis_general import *
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/base_hcb.py", line 1, in <module>
    from ._basis_general_core import hcb_basis_core_wrap
  File "~/miniconda3/lib/python3.7/site-packages/quspin/basis/basis_general/_basis_general_core/__init__.py", line 6, in <module>
    from .user_core import user_core_wrap
  File "quspin/basis/basis_general/_basis_general_core/source/general_basis_core.pyx", line 210, in init quspin.basis.basis_general._basis_general_core.user_core
AttributeError: type object 'quspin.basis.basis_general._basis_general_core.use' has no attribute '__reduce_cython__'
```

This missing cython function cannot be fixed by importing cython.

**Comment by jtschneider** [comment]
on a windows machine the issue is a little different

```python console
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import quspin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\__init__.py", line 3, in <module>
    from . import operators
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\operators\__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\operators\quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\basis\__init__.py", line 118, in <module>
    from .basis_general import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\basis\basis_general\__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\basis\basis_general\spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "C:\ProgramData\Anaconda3\lib\site-packages\quspin\basis\basis_general\base_hcb.py", line 6, in <module>
    import cProfile
  File "C:\ProgramData\Anaconda3\lib\cProfile.py", line 10, in <module>
    import profile as _pyprofile
  File "C:\Users\Jan\Documents\PhD\code\exact-diagonalisation\profile.py", line 1, in <module>
    from quspin.operators import hamiltonian
ImportError: cannot import name 'hamiltonian' from 'quspin.operators' (C:\ProgramData\Anaconda3\lib\site-packages\quspin\operators\__init__.py)
```

**Comment by weinbe58** [comment]
That's odd, could you list what you get from running: `conda list` as well as `conda info`

**Comment by jtschneider** [comment]
sure:

```bash
$ conda list
# packages in environment at /home/CPHT/jan.schneider/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
asn1crypto                1.3.0                    py37_0
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py37_0
cffi                      1.14.0           py37h2e261b9_0
chardet                   3.0.4                 py37_1003
conda                     4.8.3                    py37_0
conda-package-handling    1.6.1            py37h7b6447c_0
cryptography              2.8              py37h1ba5d50_0
cython                    0.29.17          py37he6710b0_0
dill                      0.3.1.1                  py37_0
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py37h10f8cd9_2
idna                      2.9                        py_1
intel-openmp              2020.0                      166
joblib                    0.14.1                     py_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.32.0           py37hd408876_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
ncurses                   6.2                  he6710b0_1
numba                     0.49.0           py37h0573a6f_0
numexpr                   2.7.1            py37h423224d_0
numpy                     1.18.1           py37h4f9e942_0
numpy-base                1.18.1           py37hde5b4d6_1
omp                       1.0                           0    weinbe58
openssl                   1.1.1g               h7b6447c_0
pip                       20.0.2                   py37_1
pycosat                   0.6.3            py37h7b6447c_0
pycparser                 2.20                       py_0
pyopenssl                 19.1.0                   py37_0
pysocks                   1.7.1                    py37_0
python                    3.7.7           hcf32534_0_cpython
quspin                    0.3.4           omp_py37h8bc04fc_0  [omp]  weinbe58
readline                  8.0                  h7b6447c_0
requests                  2.23.0                   py37_0
ruamel_yaml               0.15.87          py37h7b6447c_0
scipy                     1.4.1            py37h0b6359f_0
setuptools                46.1.3                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               h62c20be_1
tbb                       2020.0               hfd86e86_0
tk                        8.6.8                hbc83047_0
tqdm                      4.46.0                     py_0
urllib3                   1.25.8                   py37_0
wheel                     0.34.2                   py37_0
xz                        5.2.5                h7b6447c_0
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3
```
and
```bash
conda info

     active environment : base
    active env location : ~/miniconda3
            shell level : 1
       user config file : ~/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.12
       base environment : ~/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda3/envs
                          ~/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/2.6.32-431.29.2.el6.x86_64 scientific/6.6 glibc/2.12
                UID:GID : 1055:1055
             netrc file : None
           offline mode : False
```
(I replaced the absolute path of my home dir with `~/`)

**Comment by jtschneider** [comment]
Fixed it! 
`conda install numba=0.48.0`
did the job for me. Apparently, there is a compatability issue with the lastest version ob numba `0.49.0`

**Comment by mgbukov** [comment]
I am re-opening this; we should resolve the `numba` compatibility or others will bump into the same problem.

**Comment by weinbe58** [comment]
OK, so it appars as though numba has moved `CFunc` from `numba.ccallback` to `numba.core.ccallback` should be an easy fix, however we will have to then limit numba>=0.49.0

**Comment by mgbukov** [comment]
we can do it, but I must say that I'm not particularly fascinated with the way the `numba` guys handle backward compatibility.

**Comment by weinbe58** [comment]
This should work:

```python
try:
    from numba.ccallback import CFunc
except ModuleNotFoundError:
    from numba.core.ccallback import CFunc
```

**Comment by jerrylvx** [comment]
I tried to install numba=0.48.0. The ModuleNotFoundError is gone but replaced with another error:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-6-8e64c7d3e5da> in <module>
----> 1 from quspin.operators import hamiltonian

~\Anaconda3\lib\site-packages\quspin\__init__.py in <module>
      1 # local modules
      2 import numpy,dill
----> 3 from . import operators
      4 from . import basis
      5 from . import tools

~\Anaconda3\lib\site-packages\quspin\operators\__init__.py in <module>
     52 
     53 """
---> 54 from .quantum_operator_core import *
     55 from .quantum_LinearOperator_core import *
     56 from .hamiltonian_core import *

~\Anaconda3\lib\site-packages\quspin\operators\quantum_operator_core.py in <module>
      1 from __future__ import print_function, division, absolute_import
      2 
----> 3 from ..basis import spin_basis_1d as _default_basis
      4 from ..basis import isbasis as _isbasis
      5 

~\Anaconda3\lib\site-packages\quspin\basis\__init__.py in <module>
    116 """
    117 from .basis_1d import *
--> 118 from .basis_general import *
    119 from .base import *
    120 from .lattice import *

~\Anaconda3\lib\site-packages\quspin\basis\basis_general\__init__.py in <module>
----> 1 from .spin import spin_basis_general
      2 from .boson import boson_basis_general
      3 from .fermion import spinless_fermion_basis_general,spinful_fermion_basis_general
      4 from ._basis_general_core import (bitwise_not,bitwise_and,bitwise_or,bitwise_xor,
      5                                                 bitwise_leftshift,bitwise_rightshift,basis_zeros,basis_ones,

~\Anaconda3\lib\site-packages\quspin\basis\basis_general\spin.py in <module>
----> 1 from .base_hcb import hcb_basis_general
      2 from .base_higher_spin import higher_spin_basis_general
      3 import numpy as _np
      4 
      5 try:

~\Anaconda3\lib\site-packages\quspin\basis\basis_general\base_hcb.py in <module>
----> 1 from ._basis_general_core import hcb_basis_core_wrap
      2 from ._basis_general_core import get_basis_type,basis_zeros
      3 from .base_general import basis_general
      4 import numpy as _np
      5 from scipy.special import comb

~\Anaconda3\lib\site-packages\quspin\basis\basis_general\_basis_general_core\__init__.py in <module>
      4 from .spinless_fermion_core import spinless_fermion_basis_core_wrap
      5 from .spinful_fermion_core import spinful_fermion_basis_core_wrap
----> 6 from .user_core import user_core_wrap
      7 from .general_basis_utils import *

quspin\basis\basis_general\_basis_general_core\user_core.pyx in init quspin.basis.basis_general._basis_general_core.user_core()

~\Anaconda3\lib\site-packages\numba\ccallback.py in <module>
      9 from llvmlite import ir
     10 
---> 11 from . import utils, compiler
     12 from .caching import NullCache, FunctionCache
     13 from .dispatcher import _FunctionCompiler

~\Anaconda3\lib\site-packages\numba\compiler.py in <module>
      9 from numba import (bytecode, interpreter, postproc, typing,  utils, config,
     10                    errors,)
---> 11 from numba.targets import cpu, callconv
     12 from numba.parfor import ParforDiagnostics
     13 from numba.inline_closurecall import InlineClosureCallPass

~\Anaconda3\lib\site-packages\numba\targets\cpu.py in <module>
     12 from numba import utils, cgutils, types
     13 from numba.utils import cached_property
---> 14 from numba.targets import (
     15     callconv, codegen, externals, intrinsics, listobj, setobj, dictimpl,
     16 )

~\Anaconda3\lib\site-packages\numba\targets\listobj.py in <module>
   1069 
   1070 @overload_method(types.List, "sort")
-> 1071 def ol_list_sort(lst, key=None, reverse=False):
   1072 
   1073     _sort_check_key(key)

~\Anaconda3\lib\site-packages\numba\core\extending.py in decorate(overload_func)

~\Anaconda3\lib\site-packages\numba\core\typing\templates.py in make_overload_method_template(typ, attr, overload_func, inline)

~\Anaconda3\lib\site-packages\numba\core\typing\templates.py in make_overload_attribute_template(typ, attr, overload_func, inline, base)

AssertionError: 
```
