### ISSUE TITLE
spinful_fermion_basis_1d with tensor_basis

### ISSUE THREAD

**Issue by Fysiker007** [weinbe58/QuSpin#328]
Hi guys,

I am trying to build a superlattice of two spinful fermionic sublattices, but I am encountering problems when I try to build the Hamiltonian.

Below is a simplified version of the code that still captures the problem, which is basically that I do not know how to split the terms of the different sublattices in static. In this simple example, I just want to create a Hamiltonian that is simply the number particle of the up spins of the A sublattice. I tried adding an extra pipe (since I know there must be a pipe to separate the symbols of the up and down fermions in one sublattice), but that also did not work. 

I know that in principle I can just use four spinless_fermion_basis_1d, but I am interested in making use of the particle conservation in basis A below, in order to reach a bigger system size. Thanks a lot in advance for your help!

```
L = 6
dynamic = []
basis_A = spinful_fermion_basis_1d(L=L,Nf=(L//2,L//2))
basis_B = spinful_fermion_basis_1d(L=L)
basis = tensor_basis(basis_A,basis_B)

massTerm = [[1.0,i] for i in range(L)]
static = [["n|",massTerm]]
H = hamiltonian(static,dynamic,basis=basis)
```

and the error is

```
Traceback (most recent call last):
  File "nonAbelian.py", line 44, in <module>
    H = hamiltonian(static,dynamic,basis=basis)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/operators/hamiltonian_core.py", line 309, in __init__
    self._basis.check_hermitian(static_opstr_list, dynamic_opstr_list)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/base.py", line 412, in check_hermitian
    static_list,dynamic_list = self._get_local_lists(static,dynamic)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/base.py", line 715, in _get_local_lists
    return self._sort_local_list(static_list),self._sort_local_list(dynamic_list)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/base.py", line 692, in _sort_local_list
    sorted_op_list.append(self._sort_opstr(op))
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/tensor.py", line 817, in _sort_opstr
    op1 = self._basis_left._sort_opstr(op1)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/basis_1d/fermion.py", line 612, in _sort_opstr
    return _sort_opstr_spinful(op)
  File "/Users/Fysiker007/anaconda2/lib/python2.7/site-packages/quspin/basis/basis_1d/fermion.py", line 737, in _sort_opstr_spinful
    raise ValueError("missing '|' charactor in: {0}, {1}".format(opstr,indx))
ValueError: missing '|' charactor in: n, (0,)
```

**Comment by weinbe58** [comment]
Hello,

Unofortunately you can't actually do this with spinful_fermion_basis_1d but you can do this with spinful_fermion_basis_general but you have to use the advanced notation, which simply means that spin-up correspond to sites 0 to N-1 and spin-down are N to 2*N-1. 

Hope this helps.

**Comment by Fysiker007** [comment]
OK thank you very much!
