### ISSUE TITLE
check_symm with momentum and multiple pcon blocks throws error in py35

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#33]
The code is supposed to throw an error due to broken translation invariance at boundary but never gets to do the check. Instead, it throws an error earlier:

```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    H_fermion=hamiltonian(static_fermion,[],basis=basis_fermion,dtype=np.float64,check_pcon=False)
  File "/Users/mbukov/anaconda2/envs/py35/lib/python3.5/site-packages/quspin/operators/ops.py", line 248, in __init__
    basis.check_symm(static_opstr_list,dynamic_opstr_list)
  File "/Users/mbukov/anaconda2/envs/py35/lib/python3.5/site-packages/quspin/basis/base.py", line 429, in check_symm
    unique_opstrs = list(set( zip(*tuple(missing_ops))[0]) )
TypeError: 'zip' object is not subscriptable
```

Full script below:

```python
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d, fermion_basis_1d # Hilbert space spin basis
import numpy as np

L=8
basis_fermion = fermion_basis_1d(L=L,Nf=range(0,L+1,2),kblock=0)
J_pm=[[-1,i,i+1] for i in range(L-1)] 
J_mp=[[+1,i,i+1] for i in range(L-1)]
J_pm.append([+1,L-1,0]) # APBC
J_mp.append([-1,L-1,0]) # APBC
static_fermion =[["+-",J_pm],["-+",J_mp]]
H_fermion=hamiltonian(static_fermion,[],basis=basis_fermion,dtype=np.float64,check_pcon=False)
```

**Comment by weinbe58** [comment]
Fix added to branch ent_entropy.
