### ISSUE TITLE
Numba dependency error: ModuleNotFoundError: No module named 'numba.ccallback'

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#346]
The following error is caused when using `numba>0.48.0`; 

To avoid it in `quspin=0.3.4` downgrade `numba` to

```
conda install numba=0.48
``` 

Full traceback:

```
Traceback (most recent call last):
  File "test_libraries.py", line 4, in <module>
    from tlfi_quspin import *
  File "/Users/mgbukov/projects_ongoing/RL_MPS/environment/tlfi_quspin.py", line 1, in <module>
    from quspin.operators import hamiltonian
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/operators/__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/basis/__init__.py", line 118, in <module>
    from .basis_general import *
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/basis/basis_general/__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/basis/basis_general/spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/basis/basis_general/base_hcb.py", line 1, in <module>
    from ._basis_general_core import hcb_basis_core_wrap
  File "/Users/mgbukov/miniconda3/envs/RL_MPS/lib/python3.7/site-packages/quspin/basis/basis_general/_basis_general_core/__init__.py", line 6, in <module>
    from .user_core import user_core_wrap
  File "quspin/basis/basis_general/_basis_general_core/user_core.pyx", line 6, in init quspin.basis.basis_general._basis_general_core.user_core
ModuleNotFoundError: No module named 'numba.ccallback'
```

**Comment by stanislavvelkov** [comment]
Installing numba through pip also installs a later version of llvmlite, which causes https://github.com/mkocabas/VIBE/issues/91. Thus, in addition to numba<=0.48 you need llvmlite<=0.32.1
