### ISSUE TITLE
Conda installation issues 

### ISSUE THREAD

**Issue by FriendlyHamiltonian** [weinbe58/QuSpin#385]
I have managed to install qspin with conda. If I run
`conda list`
I get
```# 
packages in environment at /home/alex/anaconda3/envs/negativity_quspin_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.12.8            
h06a4308_0  
certifi                   2020.12.5        py37h06a4308_0  
dill                      0.3.3              pyhd3eb1b0_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py37h10f8cd9_2  
intel-openmp              2020.2                      254  
joblib                    1.0.0              pyhd3eb1b0_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.34.0           py37h269e1b5_4  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
ncurses                   6.2                  he6710b0_1  
numba                     0.51.2           py37h04863e7_1  
numexpr                   2.7.2            py37hb2eb853_0  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
openssl                   1.1.1i               h27cfd23_0  
pip                       20.3.3           py37h06a4308_0  
python                    3.7.9                h7579374_0  
quspin                    0.3.4            py37h8bc04fc_0    weinbe58
readline                  8.0                  h7b6447c_0  
scipy                     1.5.2            py37h0b6359f_0  
setuptools                51.1.2           py37h06a4308_3  
six                       1.15.0           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.3               hfd86e86_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```
So apparently it is installed. But if I import it by running `python` and importing it:
```Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from quspin.operators import hamiltonian # Hamiltonians and operators

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/operators/__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/basis/__init__.py", line 118, in <module>
    from .basis_general import *
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/basis/basis_general/__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/basis/basis_general/spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/basis/basis_general/base_hcb.py", line 1, in <module>
    from ._basis_general_core import hcb_basis_core_wrap
  File "/home/alex/anaconda3/envs/negativity_quspin_env/lib/python3.7/site-packages/quspin/basis/basis_general/_basis_general_core/__init__.py", line 6, in <module>
    from .user_core import user_core_wrap
  File "quspin/basis/basis_general/_basis_general_core/user_core.pyx", line 6, in init quspin.basis.basis_general._basis_general_core.user_core
ModuleNotFoundError: No module named 'numba.ccallback'
```

What could I be doing wrong?

**Comment by FriendlyHamiltonian** [comment]
Just saw the solution in another post and it worked like a charm. Apologies for the duplicate. 

Running `conda install numba=0.48` in the enviroment fixed this.
