### ISSUE TITLE
hermicity reports error 

### ISSUE THREAD

**Issue by JiahaoYao** [weinbe58/QuSpin#431]
The matrix generated by the following is hermitian
```python
import numpy as np 
import scipy.sparse
import scipy.linalg as la
import scipy.io

from quspin.operators import hamiltonian
from quspin.basis import spinful_fermion_basis_1d
from quspin.tools.evolution import expm_multiply_parallel

import itertools

##### define model parameters #####
basis = spinful_fermion_basis_1d(2,Nf=(1,1))

no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)

H1_term   = [[1.0j/4 * (-1)**(j+l),i,j,k,l] for i, j, k, l in itertools.product(range(2), repeat=4)]
H1_term_m = [[-1.0j/4 * (-1)**(j+l),i,j,k,l] for i, j, k, l in itertools.product(range(2), repeat=4)]
H1_static = [
        ['-+|-+', H1_term],
        ['+-|+-', H1_term_m],
        ]
H1 = hamiltonian(H1_static, [], basis=basis, dtype=np.complex128,**no_checks)

print(H1)
print(H1.toarray())
```

I can get the matrix 

```bash 
[[0.+0.j  0.+0.5j 0.+0.5j 0.+0.j ]
 [0.-0.5j 0.+0.j  0.+0.j  0.-0.5j]
 [0.-0.5j 0.+0.j  0.+0.j  0.-0.5j]
 [0.+0.j  0.+0.5j 0.+0.5j 0.+0.j ]]
```

But, if I turn on the hermicity check

```python
    H1 = hamiltonian(H1_static, [], basis=basis, dtype=np.complex128)
```

I got these error messages: 

```markdown 
hubbard_dimer_ao.py:38: UserWarning: The following static operator strings contain non-hermitian couplings: ['-+|-+', '+-|+-']
  H1 = hamiltonian(H1_static, [], basis=basis, dtype=np.complex128,)
Display all 8 non-hermitian couplings? (y or n) y
   (opstr, indices, coupling)
1. ('-+|-+', (0, 0, 0, 0), 0.25j)
2. ('+-|+-', (0, 0, 0, 0), -0.25j)
3. ('+-|+-', (0, 0, 1, 1), 0.25j)
4. ('+-|+-', (1, 1, 0, 0), 0.25j)
5. ('+-|+-', (1, 1, 1, 1), -0.25j)
6. ('-+|-+', (1, 1, 1, 1), 0.25j)
7. ('-+|-+', (1, 1, 0, 0), -0.25j)
8. ('-+|-+', (0, 0, 1, 1), -0.25j)
Traceback (most recent call last):
  File "hubbard.py", line 38, in <module>
    H1 = hamiltonian(H1_static, [], basis=basis, dtype=np.complex128,)
  File "/python3.7/site-packages/quspin/operators/hamiltonian_core.py", line 312, in __init__
    self._basis.check_hermitian(static_opstr_list, dynamic_opstr_list)
  File "/python3.7/site-packages/quspin/basis/base.py", line 518, in check_hermitian
    raise TypeError("Hamiltonian not hermitian! To turn this check off set check_herm=False in hamiltonian.")
TypeError: Hamiltonian not hermitian! To turn this check off set check_herm=False in hamiltonian.
```

My guess the hermicity check does not take into account the cancellation.

**Comment by mgbukov** [comment]
This might be related to #331 and #329
