### ISSUE TITLE
32-site basis fails

### ISSUE THREAD

**Issue by nikita-astronaut** [weinbe58/QuSpin#473]
Dear developers of quspin,

I discovered a bug in my simulations.

```
Ns = 16
basis_full = spinful_fermion_basis_general(Ns, simple_symm = False)
cdag = quantum_operator(dict(H0=[['+', [[1, 0]]]], H1=[]), basis=basis_full, check_herm = False, check_symm=False)
```

However, the code falls with

```
OMP_NUM_THREADS=8 python3 test.py
/home/fkp/astronik/spt_newmodel.py:210: UserWarning: Test for particle conservation not implemented for <class 'quspin.basis.basis_general.fermion.spinful_fermion_basis_general'>, to turn off this warning set check_pcon=False in hamiltonian
  cdag = quantum_operator(dict(H0=[['+', [[1, 0]]]], H1=[]), basis=basis_full, check_herm = False, check_symm=False)
Traceback (most recent call last):
  File "/home/fkp/astronik/spt_newmodel.py", line 333, in <module>
    main()
  File "/home/fkp/astronik/spt_newmodel.py", line 210, in main
    cdag = quantum_operator(dict(H0=[['+', [[1, 0]]]], H1=[]), basis=basis_full, check_herm = False, check_symm=False)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/operators/quantum_operator_core.py", line 172, in __init__
    O = make_static(basis,opstr_list,dtype)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/operators/_make_hamiltonian.py", line 109, in make_static
    return basis._make_matrix(static_list,dtype)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/basis/base.py", line 226, in _make_matrix
    ME,row,col = self.Op(opstr,indx,J,dtype)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/basis/base.py", line 218, in Op
    return self._Op(opstr,indx,J,dtype)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/basis/basis_general/fermion.py", line 618, in _Op
    return spinless_fermion_basis_general._Op(self,opstr,indx,J,dtype)
  File "/home/fkp/astronik/anaconda3/envs/quspin_env/lib/python3.9/site-packages/quspin/basis/basis_general/base_general.py", line 274, in _Op
    self._core.op(row,col,ME,opstr,indx,J,self._basis,self._n,self._basis_begin,self._basis_end,self._N_p)
  File "quspin/basis/basis_general/_basis_general_core/source/general_basis_core.pyx", line 224, in quspin.basis.basis_general._basis_general_core.spinful_fermion_core.general_basis_core_wrap.__pyx_fused_cpdef
TypeError: Function call with ambiguous argument types
```

Linux, 756 Gb RAM

Could you please suggest what is going possibly wrong? 32 sites is the biggest size that is yet supported, right?

Thanks a lot!

Best wishes,
Nikita

**Comment by nikita-astronaut** [comment]
With creation operator replaced with density operator, the problem still holds:
'```
cdag = quantum_operator(dict(H0=[['+-', [[1, 0, 0]]]], H1=[]), basis=basis_full)
```

**Comment by JiahaoYao** [comment]
Hi @nikita-astronaut , thanks for your questions!

On my side, I am able to run your example: 

```python 
import quspin 
from quspin.basis import spinful_fermion_basis_general # spin basis constructor
from quspin.operators import hamiltonian,quantum_operator # operators
import numpy as np
Ns = 2
basis_full = spinful_fermion_basis_general(Ns, simple_symm = False)
cdag = quantum_operator(dict(H0=[['+', [[1, 0]]]], H1=[]), basis=basis_full, check_herm = False, check_symm=False)

print(cdag.toarray())
```
Here are the outputs
```markdown
UserWarning: Test for particle conservation not implemented for <class 'quspin.basis.basis_general.fermion.spinful_fermion_basis_general'>, to turn off this warning set check_pcon=False in hamiltonian
  cdag = quantum_operator(dict(H0=[['+', [[1, 0]]]], H1=[]), basis=basis_full, check_herm = False, check_symm=False)
[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]]
```


You might need to check your installation of your `Quspin`, or reduce the `Ns` for sanity check. By the way, I am using `python 3.7`.

**Comment by nikita-astronaut** [comment]
Dear @weinbe58 ,

I implemented your fix but the problem is still there (I guess in another form).

Now I try still to perform the operation `cdag = quantum_operator(dict(H0=[['+', [[1, i] for i in range(Ns)]]], H1=[]), basis=basis_full, check_herm = False)`.

Now the code runs very slowly (30 minutes) on this operation. All this time the memory consumption is slowly increasing. As I hit 504 Gb, the code is killed by Memory requirement.

My question would be: what is the minimum RAM requirement to initialize a 32-site operator? (16 sites x 2 spins).

Thanks a lot!

**Comment by nikita-astronaut** [comment]
Upd: 750 GB RAM machine also overflown.

**Comment by nikita-astronaut** [comment]
Dear @JiahaoYao , maybe you have some feeling on why the basis creation fails on memory? Thanks a lot!

**Comment by JiahaoYao** [comment]
Hi @nikita-astronaut , thanks for asking!

I have looked into the dimension of the basis
```
Ns = 16
basis_full = spinful_fermion_basis_general(Ns, simple_symm = False)
print(basis_full.Ns)
# 4294967296
```

This implies the Hilbert dimension would be `4e9 x 4e9 ~ 1e19`. No wonder that
>  750 GB RAM machine also overflown.

**Comment by JiahaoYao** [comment]
that is probably why basis typically comes with the symmetry, as shown in the [examples](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spinful_fermion_basis_general.html).

**Comment by JiahaoYao** [comment]
> Dear @weinbe58 ,
> 
> I implemented your fix but the problem is still there (I guess in another form).
> 
> Now I try still to perform the operation `cdag = quantum_operator(dict(H0=[['+', [[1, i] for i in range(Ns)]]], H1=[]), basis=basis_full, check_herm = False)`.
> 
> Now the code runs very slowly (30 minutes) on this operation. All this time the memory consumption is slowly increasing. As I hit 504 Gb, the code is killed by Memory requirement.
> 
> My question would be: what is the minimum RAM requirement to initialize a 32-site operator? (16 sites x 2 spins).
> 
> Thanks a lot!

Try whether you can restrict the basis into some symmetry sectors and possibly this will also reduce the computation time and memory.

**Comment by mgbukov** [comment]
This is fixed in dev_0.3.7 and will appear with the next release.

**Comment by mgbukov** [comment]
new release is out; closing this
